config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  get '/dashboards', to: 'dashboards#index'

  get '/dashboards/administrateurs'
  post '/dashboards/administrateurs', to: 'dashboards#create_admin', as: 'create_admin'
  put '/dashboards/administrateurs/:email/change_state_admin', to: 'dashboards#change_state_admin', as: 'change_state_admin', :constraints => { :email => /[^\/]+/ }
  get '/dashboards/administrateurs/:email/edit', to: 'dashboards#edit_admin', as: 'edit_admin', :constraints => { :email => /[^\/]+/ }
  patch '/dashboards/administrateurs', to: 'dashboards#update_admin', as: 'update_admin'
  delete '/dashboards/administrateurs/:email', to: 'dashboards#delete_admin', as: 'delete_admin', :constraints => { :email => /[^\/]+/ }

  get '/profil/:email', to: 'pages#profil', as: 'profil', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/locations'
  post '/dashboards/locations', to: 'dashboards#create_location', as: 'create_location'
  put '/dashboards/locations/:slug/change_state_location', to: 'dashboards#change_state_location', as: 'change_state_location'
  get '/dashboards/locations/:slug/edit', to: 'dashboards#edit_location', as: 'edit_location'
  patch '/dashboards/locations', to: 'dashboards#update_location', as: 'update_location'
  get '/dashboards/locations/:slug', to: 'dashboards#show_location', as: 'show_location'
  delete '/dashboards/locations/:slug', to: 'dashboards#delete_location', as: 'delete_location'

  get '/dashboards/types'
  post '/dashboards/types', to: 'dashboards#create_type', as: 'create_type'
  get '/dashboards/types/:slug', to: 'dashboards#show_type', as: 'show_type'
  get '/dashboards/types/:slug/edit', to: 'dashboards#edit_type', as: 'edit_type'
  patch '/dashboards/types', to: 'dashboards#update_type', as: 'update_type'
  delete '/dashboards/types/:slug', to: 'dashboards#delete_type', as: 'delete_type'

  get '/dashboards/caracteristiques'  
  post '/dashboards/caracteristiques', to: 'dashboards#create_caracteristique', as: 'create_caracteristique'
  get '/dashboards/caracteristiques/:libelle', to: 'dashboards#show_caracteristique', as: 'show_caracteristique'
  get '/dashboards/caracteristiques/:libelle/edit', to: 'dashboards#edit_caracteristique', as: 'edit_caracteristique'
  patch '/dashboards/caracteristiques', to: 'dashboards#update_caracteristique', as: 'update_caracteristique'
  delete '/dashboards/caracteristiques/:libelle', to: 'dashboards#delete_caracteristique', as: 'delete_caracteristique'

  get '/dashboards/utilisateurs'
  put '/dashboards/utilisateurs/:email/change_state_user', to: 'dashboards#change_state_user', as: 'change_state_user', :constraints => { :email => /[^\/]+/ }
  delete '/dashboards/utilisateurs/:email', to: 'dashboards#delete_user', as: 'delete_user', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/reservations'
  get '/dashboards/reservations/:slug', to: 'dashboards#show_reservation', as: 'show_reservation'
  get '/dashboards/reservations/confirmer/:slug', to: 'dashboards#confirmer', as: 'confirmer'

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :caracteristiques
  resources :adresses
  
  resources :types

  resources :locations do
    get 'type', on: :member
    resources :reservations
  end

  resources :reservations do
    collection do
      get 'my_reservation', to: 'reservations/my_reservation', as: 'my_reservation'
      get 'confirmer/:slug', to: 'reservations#confirmer', as: 'confirmer'
    end
  end

  get '/users', to: 'pages#users', as: 'users'

  get '/user/:id', to: 'pages#user', as: 'user'

  get '/search', to: 'pages#search', as: 'search'

  get '/pages/query', to: 'pages#query'

  get '/adresse/:adresse', to: 'pages#adresse', as: 'adresse'

  get '/type/:type/:adresse', to: 'pages#type_adresse', as: 'type_adresse'

  get '/filter', to: 'locations#filter', as: 'filter'

  resources :notifications, only: [:index, :show]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/caracteristique.rb
class Caracteristique < ApplicationRecord
    has_and_belongs_to_many :locations
end

app/controllers/caracteristiques_controller.rb
class CaracteristiquesController < ApplicationController
  before_action :set_caracteristique, only: [:show, :edit, :update, :destroy]

  # GET /caracteristiques
  # GET /caracteristiques.json
  def index
    @caracteristiques = Caracteristique.all
  end

  # GET /caracteristiques/1
  # GET /caracteristiques/1.json
  def show
  end

  # GET /caracteristiques/new
  def new
    @caracteristique = Caracteristique.new
  end

  # GET /caracteristiques/1/edit
  def edit
  end

  # POST /caracteristiques
  # POST /caracteristiques.json
  def create
    @caracteristique = Caracteristique.new(caracteristique_params)

    respond_to do |format|
      if @caracteristique.save
        format.html { redirect_to @caracteristique, notice: 'Caracteristique was successfully created.' }
        format.json { render :show, status: :created, location: @caracteristique }
      else
        format.html { render :new }
        format.json { render json: @caracteristique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caracteristiques/1
  # PATCH/PUT /caracteristiques/1.json
  def update
    respond_to do |format|
      if @caracteristique.update(caracteristique_params)
        format.html { redirect_to @caracteristique, notice: 'Caracteristique was successfully updated.' }
        format.json { render :show, status: :ok, location: @caracteristique }
      else
        format.html { render :edit }
        format.json { render json: @caracteristique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caracteristiques/1
  # DELETE /caracteristiques/1.json
  def destroy
    @caracteristique.destroy
    respond_to do |format|
      format.html { redirect_to caracteristiques_url, notice: 'Caracteristique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caracteristique
      @caracteristique = Caracteristique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caracteristique_params
      params.require(:caracteristique).permit(:libelle, :icon)
    end
end

app/helpers/caracteristiques_helper.rb
module CaracteristiquesHelper
end

app/views/caracteristiques/_form.html.erb
<%= form_with(model: caracteristique, local: true) do |form| %>
  <% if caracteristique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caracteristique.errors.count, "error") %> prohibited this caracteristique from being saved:</h2>

      <ul>
        <% caracteristique.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group form-group">
    <%= form.text_field :libelle, placeholder: "Libelle", class: "form-control" %>
  </div>

  <div class="input-group form-group">
    <%= form.text_field :icon, placeholder: "Icon", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Création", class:"btn float-right login_btn"  %>
  </div>
<% end %>

app/views/caracteristiques/edit.html.erb
<h1>Editing Caracteristique</h1>

<%= render 'form', caracteristique: @caracteristique %>

<%= link_to 'Show', @caracteristique %> |
<%= link_to 'Back', caracteristiques_path %>

app/views/caracteristiques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caracteristiques</h1>

<table>
  <thead>
    <tr>
      <th>Libelle</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caracteristiques.each do |caracteristique| %>
      <tr>
        <td><%= caracteristique.libelle %></td>
        <td><%= caracteristique.icon %></td>
        <td><%= link_to 'Show', caracteristique %></td>
        <td><%= link_to 'Edit', edit_caracteristique_path(caracteristique) %></td>
        <td><%= link_to 'Destroy', caracteristique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caracteristique', new_caracteristique_path %>

app/views/caracteristiques/new.html.erb
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card form">
            <div class="card-header">
                <h1>Création de caracteristique</h1>
            </div>
            <div class="card-body">
                <%= render 'form', caracteristique: @caracteristique %>
            </div>
            <div class="card-footer">
                <%= link_to 'Retour', caracteristiques_path %>
            </div>
        </div>
    </div>
</div>

app/views/caracteristiques/show.html.erb
<div class="card profil-content">
  <div class="row no-gutters">
    <div class="col-md-4">
      <span class="<%= @caracteristique.icon %>" style="width: 100%; height: 50px;">
      </span>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= "#{@caracteristique.libelle}" %></h5>
        <div class="row">
            <div class="col-sm-3 profil-title">Icon</div>
            <div class="col-sm-9">
              <%= @caracteristique.icon %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>