config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  get '/dashboards', to: 'dashboards#index'

  get '/dashboards/administrateurs'
  post '/dashboards/administrateurs', to: 'dashboards#create_admin', as: 'create_admin'
  put '/dashboards/administrateurs/:email/change_state_admin', to: 'dashboards#change_state_admin', as: 'change_state_admin', :constraints => { :email => /[^\/]+/ }
  get '/dashboards/administrateurs/:email/edit', to: 'dashboards#edit_admin', as: 'edit_admin', :constraints => { :email => /[^\/]+/ }
  patch '/dashboards/administrateurs', to: 'dashboards#update_admin', as: 'update_admin'
  delete '/dashboards/administrateurs/:email', to: 'dashboards#delete_admin', as: 'delete_admin', :constraints => { :email => /[^\/]+/ }

  get '/profil/:email', to: 'pages#profil', as: 'profil', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/locations'
  post '/dashboards/locations', to: 'dashboards#create_location', as: 'create_location'
  put '/dashboards/locations/:slug/change_state_location', to: 'dashboards#change_state_location', as: 'change_state_location'
  get '/dashboards/locations/:slug/edit', to: 'dashboards#edit_location', as: 'edit_location'
  patch '/dashboards/locations', to: 'dashboards#update_location', as: 'update_location'
  get '/dashboards/locations/:slug', to: 'dashboards#show_location', as: 'show_location'
  delete '/dashboards/locations/:slug', to: 'dashboards#delete_location', as: 'delete_location'

  get '/dashboards/types'
  post '/dashboards/types', to: 'dashboards#create_type', as: 'create_type'
  get '/dashboards/types/:slug', to: 'dashboards#show_type', as: 'show_type'
  get '/dashboards/types/:slug/edit', to: 'dashboards#edit_type', as: 'edit_type'
  patch '/dashboards/types', to: 'dashboards#update_type', as: 'update_type'
  delete '/dashboards/types/:slug', to: 'dashboards#delete_type', as: 'delete_type'

  get '/dashboards/caracteristiques'  
  post '/dashboards/caracteristiques', to: 'dashboards#create_caracteristique', as: 'create_caracteristique'
  get '/dashboards/caracteristiques/:libelle', to: 'dashboards#show_caracteristique', as: 'show_caracteristique'
  get '/dashboards/caracteristiques/:libelle/edit', to: 'dashboards#edit_caracteristique', as: 'edit_caracteristique'
  patch '/dashboards/caracteristiques', to: 'dashboards#update_caracteristique', as: 'update_caracteristique'
  delete '/dashboards/caracteristiques/:libelle', to: 'dashboards#delete_caracteristique', as: 'delete_caracteristique'

  get '/dashboards/utilisateurs'
  put '/dashboards/utilisateurs/:email/change_state_user', to: 'dashboards#change_state_user', as: 'change_state_user', :constraints => { :email => /[^\/]+/ }
  delete '/dashboards/utilisateurs/:email', to: 'dashboards#delete_user', as: 'delete_user', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/reservations'
  get '/dashboards/reservations/:slug', to: 'dashboards#show_reservation', as: 'show_reservation'
  get '/dashboards/reservations/confirmer/:slug', to: 'dashboards#confirmer', as: 'confirmer'

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :caracteristiques
  resources :adresses
  
  resources :types

  resources :locations do
    get 'type', on: :member
    resources :reservations
  end

  resources :reservations do
    collection do
      get 'my_reservation', to: 'reservations/my_reservation', as: 'my_reservation'
      get 'confirmer/:slug', to: 'reservations#confirmer', as: 'confirmer'
    end
  end

  get '/users', to: 'pages#users', as: 'users'

  get '/user/:id', to: 'pages#user', as: 'user'

  get '/search', to: 'pages#search', as: 'search'

  get '/pages/query', to: 'pages#query'

  get '/adresse/:adresse', to: 'pages#adresse', as: 'adresse'

  get '/type/:type/:adresse', to: 'pages#type_adresse', as: 'type_adresse'

  get '/filter', to: 'locations#filter', as: 'filter'

  resources :notifications, only: [:index, :show]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = current_user.types.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:libelle, :etat, :image, :user_id)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with(model: @type, local: true) do |form| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
        <% @type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group form-group">
    <%= form.text_field :libelle, class: "form-control", placeholder: 'Libelle' %>
  </div>

  <div class="input-group form-group">
    <%= form.label :etat %>
    <%= form.check_box :etat %>
  </div>

  <div class="input-group form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="input-group form-group">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="form-group">
    <%= form.submit "Création", class: "btn float-right login_btn" %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Libelle</th>
      <th>Etat</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.libelle %></td>
        <td><%= type.etat %></td>
        <td><%= type.user_id %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card form">
            <div class="card-header">
                <h1>Création de type</h1>
            </div>
            <div class="card-body">
                <%= render 'form', location: @location %>
            </div>
            <div class="card-footer">
                <%= link_to 'Retour', locations_path %>
            </div>
        </div>
    </div>
</div>

app/views/types/show.html.erb
<div class="card profil-content">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag @type.image_url, class: "card-img profil-image", alt: "..." %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= "#{@type.libelle}" %></h5>
        <div class="row">
            <div class="col-sm-3 profil-title">Etat</div>
            <div class="col-sm-9">
                <% if @type.etat == true %>
                    <span class="badge badge-success">
                        Activer
                    </span>
                <% else %>
                    <span class="badge badge-danger">
                        Desactiver
                    </span>
                <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>