config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  get '/dashboards', to: 'dashboards#index'

  get '/dashboards/administrateurs'
  post '/dashboards/administrateurs', to: 'dashboards#create_admin', as: 'create_admin'
  put '/dashboards/administrateurs/:email/change_state_admin', to: 'dashboards#change_state_admin', as: 'change_state_admin', :constraints => { :email => /[^\/]+/ }
  get '/dashboards/administrateurs/:email/edit', to: 'dashboards#edit_admin', as: 'edit_admin', :constraints => { :email => /[^\/]+/ }
  patch '/dashboards/administrateurs', to: 'dashboards#update_admin', as: 'update_admin'
  delete '/dashboards/administrateurs/:email', to: 'dashboards#delete_admin', as: 'delete_admin', :constraints => { :email => /[^\/]+/ }

  get '/profil/:email', to: 'pages#profil', as: 'profil', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/locations'
  post '/dashboards/locations', to: 'dashboards#create_location', as: 'create_location'
  put '/dashboards/locations/:slug/change_state_location', to: 'dashboards#change_state_location', as: 'change_state_location'
  get '/dashboards/locations/:slug/edit', to: 'dashboards#edit_location', as: 'edit_location'
  patch '/dashboards/locations', to: 'dashboards#update_location', as: 'update_location'
  get '/dashboards/locations/:slug', to: 'dashboards#show_location', as: 'show_location'
  delete '/dashboards/locations/:slug', to: 'dashboards#delete_location', as: 'delete_location'

  get '/dashboards/types'
  post '/dashboards/types', to: 'dashboards#create_type', as: 'create_type'
  get '/dashboards/types/:slug', to: 'dashboards#show_type', as: 'show_type'
  get '/dashboards/types/:slug/edit', to: 'dashboards#edit_type', as: 'edit_type'
  patch '/dashboards/types', to: 'dashboards#update_type', as: 'update_type'
  delete '/dashboards/types/:slug', to: 'dashboards#delete_type', as: 'delete_type'

  get '/dashboards/caracteristiques'  
  post '/dashboards/caracteristiques', to: 'dashboards#create_caracteristique', as: 'create_caracteristique'
  get '/dashboards/caracteristiques/:libelle', to: 'dashboards#show_caracteristique', as: 'show_caracteristique'
  get '/dashboards/caracteristiques/:libelle/edit', to: 'dashboards#edit_caracteristique', as: 'edit_caracteristique'
  patch '/dashboards/caracteristiques', to: 'dashboards#update_caracteristique', as: 'update_caracteristique'
  delete '/dashboards/caracteristiques/:libelle', to: 'dashboards#delete_caracteristique', as: 'delete_caracteristique'

  get '/dashboards/utilisateurs'
  put '/dashboards/utilisateurs/:email/change_state_user', to: 'dashboards#change_state_user', as: 'change_state_user', :constraints => { :email => /[^\/]+/ }
  delete '/dashboards/utilisateurs/:email', to: 'dashboards#delete_user', as: 'delete_user', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/reservations'
  get '/dashboards/reservations/:slug', to: 'dashboards#show_reservation', as: 'show_reservation'
  get '/dashboards/reservations/confirmer/:slug', to: 'dashboards#confirmer', as: 'confirmer'

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :caracteristiques
  resources :adresses
  
  resources :types

  resources :locations do
    get 'type', on: :member
    resources :reservations
  end

  resources :reservations do
    collection do
      get 'my_reservation', to: 'reservations/my_reservation', as: 'my_reservation'
      get 'confirmer/:slug', to: 'reservations#confirmer', as: 'confirmer'
    end
  end

  get '/users', to: 'pages#users', as: 'users'

  get '/user/:id', to: 'pages#user', as: 'user'

  get '/search', to: 'pages#search', as: 'search'

  get '/pages/query', to: 'pages#query'

  get '/adresse/:adresse', to: 'pages#adresse', as: 'adresse'

  get '/type/:type/:adresse', to: 'pages#type_adresse', as: 'type_adresse'

  get '/filter', to: 'locations#filter', as: 'filter'

  resources :notifications, only: [:index, :show]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_foot.html.erb
<footer>
  Copyright &copy;2020 Tout droit reservés | Cette application est faite avec <i class="fas fa-heart" aria-hidden="true"></i> par Oumar MAIGA
<footer>

app/views/pages/_head.html.erb
<header>
    <!--Bar de navigation-->
        <div class="background">
            <div class="layer">


        <% if notice || alert %>
          <div class="info">
            <% if notice %>
            <div class="alert alert-success" role="alert">
              <%= notice %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <% end %>
            <% if alert %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <% end %>
          </div>
        <% end %>

                <div class="titre">
                    Reserver vos appartement à Bamako et aux environs
                </div>
                <div class="search">
                        <%= form_tag(search_path, method: :get, class: 'form-inline') do %>
                            <div id="search-data" class="form-row search-bar" data-adresses="<%= @adresses.to_json %>">
                                <div class="form-group">
                                    <%= text_field_tag :query, nil, class: "form-control", autocomplete: 'off', placeholder: "Quartier..." %>
                                </div>
                                &nbsp;&nbsp;
                                <div class="form-group">
                                    <input type="text" id="debut" class="form-control flatpickr-input" placeholder="Date de debut" name="debut" />
                                </div>
                                &nbsp;&nbsp;
                                <div class="form-group">
                                    <input type="text" id="fin" class="form-control flatpickr-input" placeholder="Date de fin" name="fin" />
                                </div>
                                &nbsp;&nbsp;
                                    <!--<%= number_field_tag :nombre_personne %>-->
                                <div class="form-group">
                                    <%= submit_tag 'Rechercher', :class => 'btn btn-outline-custom' %>
                                </div>
                            </div>
                        <% end %>
                </div>
            </div>
        </div>
</header>

app/views/pages/_nav.html.erb
<nav class="navbar navbar-expand-lg navigation" role="navigation">
    <!-- Brand -->
        <a class="navbar-brand" href="/">APPART</a>
          <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#nav" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fas fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="nav">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <%= link_to "Locations", locations_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">A propos</a>
                    </li>
                    <% if user_signed_in? %>
                        <% if Admin? %>
                            <li class="nav-item">
                                <a class="nav-link" href="<%= notifications_path %>">
                                    Notifications <span class="badge badge-danger"><%= notification_non_vue.to_s %></span>
                                </a>
                            </li>
                            <li class="nav-item"> 
                                <%= link_to "Les reservations", reservations_path, class: "nav-link" %>
                            </li>
                            <li class="nav-item"> 
                                <%= link_to "Users", users_path, class: "nav-link" %>
                            </li>
                        <% else %>
                            <li class="nav-item">
                                <%= link_to "Mes reservations", my_reservation_reservations_path, class: "nav-link" %>
                            </li>
                        <% end %>
                    <% end %>
                </ul>
                <ul class=" navbar-nav navbar-right">
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to  "Deconnexion", destroy_user_session_path, method: :DELETE, data: { confirm:'Voulez-vous vous deconnecter ?' }, class: 'btn btn-login nav-link', type: "button" %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to  "Inscription", new_user_registration_path, class: 'btn btn-login btn-md nav-link', type: "button" %>
                        </li>
                        &nbsp;&nbsp;
                        <li class="nav-item">
                            <%= link_to  "Connexion", new_user_session_path, class: 'btn btn-login btn-md nav-link', type: "button" %>
                        </li>
                    <% end %>
                </ul>
        </div>
</nav>

app/views/pages/_query.html.erb
<% @adresses.each do |adresse| %>
    <li>
        <a href="#"><%= adresse.adresse %></a>
    </li>
<% end %>

app/views/pages/_search.html.erb
<div class="search-container">
    <h3 class="text-center">Recherche</h3>
        <%= form_tag(search_path, method: :get) do %>
            <div id="search-data" class="input-field search-bar" data-adresses="<%= @adresses.to_json %>">
                <div class="form-group">
                    <%= text_field_tag :query, nil, autocomplete: 'off', placeholder: "Quartier...", class: "form-control" %>
                </div>
                <div class="form-group">
                    <label for="debut">Du</label>
                    <input type="text" id="debut" class="flatpickr-input form-control" placeholder="Date de debut" name="debut" />
                </div>
                <div class="form-group">
                    <label for="fin">Au</label>
                    <input type="text" id="fin" class="flatpickr-input form-control" placeholder="Date de fin" name="fin" class="form-control" />
                </div>
                    <!--<%= number_field_tag :nombre_personne %>-->
                <div class="form-group">
                    <%= submit_tag 'Rechercher', :class => 'btn btn-outline-custom btn-md' %>
                </div>
            </div>
        <% end %>
</div>

app/views/pages/dashboard.html.erb
    <% content_for :dashboard do %>
    <!--Sidebar-->
        <div class="col-lg-2 col-md-3 d-none d-md-block">
            <div class="dashboard-sidebar">
                <a class="navbar-brand" href="/dashboards">Tableau de board</a>
                <nav class="dashboard-sidebar-nav">
                    <ul class="nav navbar-nav dashboard-side-item"> 
                        <% if Super_admin? %>
                            <li class="nav-item">
                                <a href="/dashboards/administrateurs" class="nav-link">Administrateur</a>
                            </li>
                        <% end %>
                        <li class="nav-item">
                            <a href="/dashboards/utilisateurs" class="nav-link">Utilisateur</a>
                        </li>
                        <% if Super_admin? %>
                            <li class="nav-item">
                                <a href="/dashboards/types" class="nav-link">Type</a>
                            </li>
                        <% end %>
                        <li class="nav-item">
                            <a href="/dashboards/locations" class="nav-link">Location</a>
                        </li>
                        <li class="nav-item">
                            <a href="/dashboards/reservations" class="nav-link">Reservation</a>
                        </li>
                        <% if Super_admin? %>
                            <li class="nav-item">
                                <a href="/dashboards/caracteristiques" class="nav-link">Caracteristique</a>
                            </li>
                        <% end %>
                    </ul>
                </nav>
            </div>
        </div>
        
    <!-- Navigation -->
        <div class="col-lg-10 col-md-9 col-sm-12 offset-md-3 offset-lg-2">
            <nav role="navigation" class="navbar  navbar-expand-lg dashborad-navigation fixed-top">
                <a class="navbar-brand" href="/">APPART</a>
                <!-- Toggler/collapsibe Button -->
                <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#navDashboard" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fas fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navDashboard">
                    <ul class="nav navbar-nav">
                        <form method="GET" class="form-inline">
                            <input type="search" placeholder="Search" name="search" id="search" class="form-control" />
                        </form>
                        <li class="nav-item">
                            <span class="nav-link" id="time"></span>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link"><span class="fas fa-bell dashboard-icon"></span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="profil" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= !current_user.nom.nil? && !current_user.prenom.nil? ? " #{current_user.nom} #{current_user.prenom}" : current_user.email %></a>
                            <div class="dropdown-menu" arial-labelledby="profil" data-target="#profil">
                                <a class="dropdown-item" href="<%= profil_path(current_user.email) %>">Profil</a>
                                <a class="dropdown-item" href="#">Autre</a>
                                <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Deconnecter</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

        <!--Body-->
    <div class="col-lg-10 col-md-9 offset-md-3 offset-lg-2 contenu">
    <!-- Sidebar-Navigation Petit ecran -->
        <div class="d-sm-block d-md-none">
            <nav role="navigation" class="navbar dashborad-sidebar-navigation">
                <a class="navbar-brand" href="/dashboards">Tableau de board</a>
                <!-- Toggler/collapsibe Button -->
                <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#dashborad-sidebar-navigation" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fas fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="dashborad-sidebar-navigation">
                <nav class="dashboard-sidebar-nav">
                    <ul class="nav navbar-nav dashboard-side-item"> 
                    <% if Super_admin? %>
                        <li class="nav-item">
                            <a href="/dashboards/administrateurs" class="nav-link">Administrateur</a>
                        </li>
                    <% end %>
                        <li class="nav-item">
                            <a href="/dashboards/utilisateurs" class="nav-link">Utilisateur</a>
                        </li>
                        <li class="nav-item">
                            <a href="/dashboards/types" class="nav-link">Type</a>
                        </li>
                        <li class="nav-item">
                            <a href="/dashboards/locations" class="nav-link">Location</a>
                        </li>
                        <li class="nav-item">
                            <a href="/dashboards/reservations" class="nav-link">Reservation</a>
                        </li>
                        <li class="nav-item">
                            <a href="/dashboards/caracteristiques" class="nav-link">Caracteristique</a>
                        </li>
                    </ul>
                </nav>
                </div>
            </nav>
        </div>
        <div class="dashboard-container">
            <% if content_for?(:dashboard_content) %>
                <%= yield :dashboard_content %>
            <% end %>
        </div>
    </div>
    <% end %>

app/views/pages/index.html.erb
    <!-- Head -->
    <div class="row">
        <div class="col-12">
            <%= render 'pages/head' %>
        </div>
    </div>

    <!-- Body -->
    <div class="container">

    <!-- Type -->
    <section id="section_type" style="margin-top: 40px;">
        <h2 class="title">Type de location</h2>
        <p class="text-title-bar"></p>
        <p class="text-muted">
            Reserver des appartments pour des logements et des magasins pour ventes ou stocks
        </p>
        <div class="row">
            <div class="col-12">
                <div class="card-group">
                    <div class="row w-100">
                        <% @types.each do |type| %>
                            <div class="col-6 col-md-4">
                                <div class="card">
                                    <a href="<%= type_location_path(type.slug) %>">
                                        <%= image_tag type.image_url, class: "card-img-top", alt: type.libelle, id: "type-image"%>
                                    </a>
                                    <div class="card-body">
                                        <h5 class="card-title"><%= type.libelle %></h5>
                                        <p class="card-text"><%= Location.where(type: type.id).count %> <%= type.libelle %></p>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Location -->
    <%= render 'locations/locations' %>

    <!-- Par quartier --> 
    <section style="margin-top: 40px;">
        <h2 class="title">Destinations populaires</h2>
        <p class="text-title-bar"></p>
        <div class="row">
            <div class="col-12">
                <div class="card-group">
                    <div class="row w-100">
                        <% @adresses.each do |adresse| %>
                        <!-- Recuperation de l'image d'un adresse -->
                            <% 
                                @location_adresse = Location.where(adresse: adresse).first
                                @image = Image.where(location_id: @location_adresse).first
                            %>
                            <div class="col-4 col-md-3">
                                <div class="card adresse-content">
                                    <a href="<%= adresse_path(adresse) %>">
                                        <%= image_tag @image.libelle_url, class: "card-img-top image-adresse", alt: adresse %>
                                    </a>
                                    <div class="card-body">
                                        <h5 class="card-title"><i class="fas fa-map-marker-alt"></i>  <%= link_to adresse, adresse_path(adresse) %></h5>
                                        <p class="card-text"><%= Location.where(adresse: adresse).count %> locations</p>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

app/views/pages/profil.html.erb
<% content_for :dashboard_content do %>
<div class="card profil-content">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag @user.image_url, class: "card-img profil-image", alt: "..." if @user.image.present? %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= "#{@user.nom} #{@user.prenom}" %></h5>
        <div class="row">
            <div class="col-5 col-sm-3 profil-title">Adresse</div>
            <div class="col-7 col-sm-9"><%= @user.adresse %></div>
        </div>
        <div class="row">
            <div class="col-5 col-sm-3 profil-title">Email</div>
            <div class="col-7 col-sm-9"><%= @user.email %></div>
        </div>
        <div class="row">
            <div class="col-5 col-sm-3 profil-title">Telephone</div>
            <div class="col-7 col-sm-9"><%= @user.telephone %></div>
        </div>
        <div class="row">
            <div class="col-5 col-sm-3 profil-title">Categorie</div>
            <div class="col-7 col-sm-9"><%= @user.categorie %></div>
        </div>
        <div class="row">
            <div class="col-5 col-sm-3 profil-title">Etat</div>
            <div class="col-7 col-sm-9">
                <% if @user.etat == true %>
                    <span class="badge badge-success">
                        Activer
                    </span>
                <% else %>
                    <span class="badge badge-danger">
                        Desactiver
                    </span>
                <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/pages/user.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-8">
            <%= "#{@user.nom} #{@user.prenom}" %><br>
            <%= @user.email %><br>
            <%= @user.adresse %><br>
        </div>
    </div>
</div>