config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  get '/dashboards', to: 'dashboards#index'

  get '/dashboards/administrateurs'
  post '/dashboards/administrateurs', to: 'dashboards#create_admin', as: 'create_admin'
  put '/dashboards/administrateurs/:email/change_state_admin', to: 'dashboards#change_state_admin', as: 'change_state_admin', :constraints => { :email => /[^\/]+/ }
  get '/dashboards/administrateurs/:email/edit', to: 'dashboards#edit_admin', as: 'edit_admin', :constraints => { :email => /[^\/]+/ }
  patch '/dashboards/administrateurs', to: 'dashboards#update_admin', as: 'update_admin'
  delete '/dashboards/administrateurs/:email', to: 'dashboards#delete_admin', as: 'delete_admin', :constraints => { :email => /[^\/]+/ }

  get '/profil/:email', to: 'pages#profil', as: 'profil', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/locations'
  post '/dashboards/locations', to: 'dashboards#create_location', as: 'create_location'
  put '/dashboards/locations/:slug/change_state_location', to: 'dashboards#change_state_location', as: 'change_state_location'
  get '/dashboards/locations/:slug/edit', to: 'dashboards#edit_location', as: 'edit_location'
  patch '/dashboards/locations', to: 'dashboards#update_location', as: 'update_location'
  get '/dashboards/locations/:slug', to: 'dashboards#show_location', as: 'show_location'
  delete '/dashboards/locations/:slug', to: 'dashboards#delete_location', as: 'delete_location'

  get '/dashboards/types'
  post '/dashboards/types', to: 'dashboards#create_type', as: 'create_type'
  get '/dashboards/types/:slug', to: 'dashboards#show_type', as: 'show_type'
  get '/dashboards/types/:slug/edit', to: 'dashboards#edit_type', as: 'edit_type'
  patch '/dashboards/types', to: 'dashboards#update_type', as: 'update_type'
  delete '/dashboards/types/:slug', to: 'dashboards#delete_type', as: 'delete_type'

  get '/dashboards/caracteristiques'  
  post '/dashboards/caracteristiques', to: 'dashboards#create_caracteristique', as: 'create_caracteristique'
  get '/dashboards/caracteristiques/:libelle', to: 'dashboards#show_caracteristique', as: 'show_caracteristique'
  get '/dashboards/caracteristiques/:libelle/edit', to: 'dashboards#edit_caracteristique', as: 'edit_caracteristique'
  patch '/dashboards/caracteristiques', to: 'dashboards#update_caracteristique', as: 'update_caracteristique'
  delete '/dashboards/caracteristiques/:libelle', to: 'dashboards#delete_caracteristique', as: 'delete_caracteristique'

  get '/dashboards/utilisateurs'
  put '/dashboards/utilisateurs/:email/change_state_user', to: 'dashboards#change_state_user', as: 'change_state_user', :constraints => { :email => /[^\/]+/ }
  delete '/dashboards/utilisateurs/:email', to: 'dashboards#delete_user', as: 'delete_user', :constraints => { :email => /[^\/]+/ }

  get '/dashboards/reservations'
  get '/dashboards/reservations/:slug', to: 'dashboards#show_reservation', as: 'show_reservation'
  get '/dashboards/reservations/confirmer/:slug', to: 'dashboards#confirmer', as: 'confirmer'

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :caracteristiques
  resources :adresses
  
  resources :types

  resources :locations do
    get 'type', on: :member
    resources :reservations
  end

  resources :reservations do
    collection do
      get 'my_reservation', to: 'reservations/my_reservation', as: 'my_reservation'
      get 'confirmer/:slug', to: 'reservations#confirmer', as: 'confirmer'
    end
  end

  get '/users', to: 'pages#users', as: 'users'

  get '/user/:id', to: 'pages#user', as: 'user'

  get '/search', to: 'pages#search', as: 'search'

  get '/pages/query', to: 'pages#query'

  get '/adresse/:adresse', to: 'pages#adresse', as: 'adresse'

  get '/type/:type/:adresse', to: 'pages#type_adresse', as: 'type_adresse'

  get '/filter', to: 'locations#filter', as: 'filter'

  resources :notifications, only: [:index, :show]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_admin_changed, only: [:change_state_admin, :edit_admin, :update_admin, :delete_admin]
  before_action :set_location_changed, only: [:change_state_location, :edit_location, :update_location, :show_location, :delete_location]
  before_action :set_type_changed, only: [:change_state_type, :edit_type, :update_type, :delete_type]
  before_action :set_carateristique_changed, only: [:edit_caracteristique, :update_caracteristique, :show_caracteristique, :delete_caracteristique]
  before_action :set_reservation, only: [:confirmer, :show_reservation]
  before_action :set_user_changed, only: [:change_state_user, :delete_user]


  def index
  end

  def locations
    @location = Location.new
    @locations = Location.all
  end

  def create_location

    location_params = params.require(:location).permit(:titre, :adresse, :description, :etat, :prix, :duree, :type_id, :nombre_adulte, :nombre_enfant, :nombre_salon, :nombre_chamber, :nombre_toillete, :nom_bailleur, :email_bailleur, :telephone_bailleur, :adresse_bailleur, :user_id, images_attributes: [:id, :location, :libelle], caracteristique_ids: [])

    params[:location][:adresse].inspect
      @location = current_user.locations.new(location_params) if user_signed_in?

    respond_to do |format|
      if @location.save
        # Enregistrement des images de l'appartement

        if is_image?
          params[:images]['libelle'].each do |a|
            @image = @location.images.create!(:libelle => a)
          end
        end

        format.html { redirect_to show_location_path(@location.slug), notice: 'Location créée avec succès.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH  /dashboards/locations
  def change_state_location
    @location = Location.new
    @locations = Location.all

    if @location_changed.etat == true
      @location_changed.update(etat: false)
      redirect_to dashboards_locations_path
    else
      @location_changed.update(etat: true)
      redirect_to dashboards_locations_path
    end
  end
  
  # GET /dashboards/locations/1/edit
  def edit_location
    @location = @location_changed
    @locations = Location.all
    render 'locations'
  end

  # PATCH /dashboards/locations/1
  def update_location
    @location = Location.new
    @locations = Location.all
    
    if @location_changed.update(location_params)
      redirect_to dashboards_locations_path
    else
      @location = @location_changed
      render 'locations', notice: "Mise à jour non effectuée"
    end
  end

  def show_location
    @location = @location_changed

    @reservation = Reservation.new
    
    @images = Image.where(location_id: @location)
    @image_last = @images.last

    # Autocomplete
    @adresses = Location.distinct.pluck(:adresse)
  end

  # DELETE /dashboards/locations/1
  def delete_location
    if @location_changed.destroy
      redirect_to dashboards_locations_path, notice: "Administrateur a été supprimer"
    end
  end

  def is_image?
    params[:images] != nil
  end
  
  def types
    @types = Type.all
    @type = Type.new
  end

  def create_type
    type_params = params.require(:type).permit(:libelle, :etat, :image, :user_id)
    @type = current_user.types.new(type_params)
    
    if @type.save
      redirect_to dashboards_types_path, notice: "Type a été ajouté"
    else
      render 'types'
    end

  end

  def show_type
    @type = Type.find_by(slug: params[:slug])
  end

  def edit_type
    @type = @type_changed
    @types = Type.all
    render 'types'
  end

  def update_type
    @type = Type.new
    @types = Type.all
    
    if @type_changed.update(type_params)
      redirect_to dashboards_types_path
    else
      @type = @type_changed
      render 'types', notice: "Mise à jour non effectuée"
    end
  end

  def delete_type
    @type = Type.find_by_slug(params[:slug])
    if @type.destroy
      redirect_to dashboards_types_path, notice: "Type a été supprimer"
    end
  end

  def caracteristiques
    @caracteristiques = Caracteristique.all
    @caracteristique = Caracteristique.new
  end

  def create_caracteristique
    caracteristique_params = params.require(:caracteristique).permit(:libelle, :icon)
    @caracteristique = Caracteristique.new(caracteristique_params)
    
    if @caracteristique.save
      redirect_to dashboards_caracteristiques_path, notice: 'Caracteristique a bien été créée.'
    else
      render 'caracteristiques'
    end

  end

  def show_caracteristique
    @caracteristique = @caracteristique_changed
  end

  def edit_caracteristique
    @caracteristique = @caracteristique_changed
    @caracteristiques = Caracteristique.all
    render 'caracteristiques'
  end

  def update_caracteristique
    @caracteristique = Caracteristique.new
    @caracteristiques = Caracteristique.all
    
    if @caracteristique_changed.update(caracteristique_params)
      redirect_to dashboards_caracteristiques_path
    else
      @caracteristique = @caracteristique_changed
      render 'caracteristiques', notice: "Mise à jour non effectuée"
    end
  end

  def delete_caracteristique
    @caracteristique = Caracteristique.find_by_libelle(params[:libelle])
    if @caracteristique.destroy
      redirect_to dashboards_caracteristiques_path, notice: "Caracteristique a été supprimer"
    end
  end

  # GET  /dashboards/administrateurs
  def administrateurs
    @admin = User.new
    @admins = User.where(categorie: 'Administrateur')
  end

  def create_admin
    @admin = User.new(admin_params)
    
    if @admin.save
      redirect_to dashboards_administrateurs_path, notice: "#{@admin.categorie} a été ajouté"
    else
      render 'administrateurs'
    end

  end

  # PATCH  /dashboards/administrateurs
  def change_state_admin
    @admin = User.new
    @admins = User.where(categorie: 'Administrateur')

    if @admin_changed.etat == true
      @admin_changed.update(etat: false)
      redirect_to dashboards_administrateurs_path
    else
      @admin_changed.update(etat: true)
      redirect_to dashboards_administrateurs_path
    end
  end
  
  # GET /dashboards/administrateurs/1/edit
  def edit_admin
    @admin = @admin_changed
    @admins = User.where(categorie: 'Administrateur')
    render 'administrateurs'
  end

  # PATCH /dashboards/administrateurs/1
  def update_admin
    @admin = User.new
    @admins = User.where(categorie: 'Administrateur')
    admin_params = params.require(:user).permit(:nom, :prenom, :email, :telephone, :adresse, :categorie, :image, :etat)

    if @admin_changed.update(admin_params)
      redirect_to dashboards_administrateurs_path
    else
      @admin = @admin_changed
      render 'administrateurs', notice: "Mise à jour non effectuée"
    end
  end

  # DELETE /dashboards/administrateurs/1
  def delete_admin
    if @admin_changed.destroy
      redirect_to dashboards_administrateurs_path, notice: "Administrateur a été supprimer"
    end
  end


  # GET /dashboards/administrateurs/1
  def profil

  end
  def utilisateurs
    @users = User.where(categorie: 'Utilisateur')
  end

  # PATCH  /dashboards/utilisateur
  def change_state_user
    @user = User.new
    @users = User.where(categorie: 'Utilisateur')

    if @user_changed.etat == true
      @user_changed.update(etat: false)
      redirect_to dashboards_utilisateurs_path
    else
      @user_changed.update(etat: true)
      redirect_to dashboards_utilisateurs_path
    end
  end

  # DELETE /dashboards/utilisateurs/1
  def delete_user
    if @user_changed.destroy
      redirect_to dashboards_utilisateurs_path, notice: "Utilisateur a été supprimer"
    end
  end


  def reservations
    @reservations = Reservation.all
  end

  def show_reservation
    @images = Image.where(location_id: @reservation.location)
    @image = @images.last
  end

  def confirmer
    @reservation.update(confirmer: :true)
    ReservationMailer.reservation_confirmer(@reservation).deliver_now
    respond_to do |format|
      format.html { redirect_to show_reservation_path(@reservation.slug), notice: "Un mail confirmation a été envoyé à #{@reservation.email}" }
    end
  end


  def admin_params
    params.require(:user).permit(:nom, :prenom, :email, :password, :telephone, :adresse, :categorie, :image, :etat)
  end

  def location_params    
    params.require(:location).permit(:titre, :adresse, :description, :etat, :prix, :duree, :type_id, :nombre_adulte, :nombre_enfant, :nombre_salon, :nombre_chamber, :nombre_toillete, :nom_bailleur, :email_bailleur, :telephone_bailleur, :adresse_bailleur, :user_id, images_attributes: [:id, :location, :libelle], caracteristique_ids: [])
  end

  def type_params
    params.require(:type).permit(:libelle, :etat, :image, :user_id)
  end

  def caracteristique_params
    params.require(:caracteristique).permit(:libelle, :icon)
  end
  
  def set_admin_changed
    @admin_changed = User.find_by_email(params[:email])
  end

  def set_location_changed
    @location_changed = Location.find_by_slug(params[:slug])
  end

  def set_user_changed
    @user_changed = User.find_by_email(params[:email])
  end

  def set_type_changed
    @type_changed = Type.find_by_slug(params[:slug])
  end

  def set_carateristique_changed
    @caracteristique_changed = Caracteristique.find_by_libelle(params[:libelle])
  end

  def set_reservation
    @reservation = Reservation.find_by_slug(params[:slug])
  end


end

app/helpers/dashboards_helper.rb
module DashboardsHelper


  def Super_admin?
    current_user.categorie === "Super-administrateur"
  end

  def Admin?
    current_user.categorie === "Administrateur"
  end


end

app/views/dashboards/administrateurs.html.erb
<% content_for :dashboard_content do %>
<section class="dashboard-form">
    <%= form_for @admin, url: create_admin_path, :html => {class: "dashboard-form-content"}  do |form| %>
        <div class="container">
            <% unless params[:email] %>
                <h3>Création d'une administrateur</h3>
            <% else %>
                <h3>Modification de l'administrateur</h3>
            <% end %>
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="input-group form-group">
                        <%= form.text_field :nom, placeholder: "NOM", class: "form-control" %>
                    </div>
                    <div class="input-group form-group">
                        <%= form.text_field :prenom, placeholder: "PRENOM", class: "form-control" %>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="input-group form-group">
                        <%= form.text_field :telephone, placeholder: "TELEPHONE", class: "form-control" %>
                    </div>
                    <div class="input-group form-group">
                        <%= form.text_field :adresse, placeholder: "ADRESSE", class: "form-control" %>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="input-group form-group">
                        <%= form.email_field :email, placeholder: "Email", class: "form-control" %>
                    </div>
                    <% unless params[:email] %>
                        <div class="input-group form-group">
                            <%= form.text_field :password, placeholder: "PASSWORD", class: "form-control" %>
                        </div>
                    <% else %>
                        <div class="input-group form-group">
                            <input type="text" placeholder= "***************" class="form-control" readonly/>
                        </div>
                    <% end %>
                </div>
                <input type="hidden" name="email" value="<%=params[:email]%>" />
                <div class="col-lg-3 col-md-6">
                    <div class="input-group form-group">
                        <span class="input-group-text">Image</span>
                        <%= form.file_field :image, class: "form-control" %>
                    </div>
                    <div class="input-group form-group">
                        <span class="input-group-text">Categorie</span>
                        <%= form.select :categorie, ['Administrateur'], {}, {class: "form-control"} %>
                    </div>
                </div>
                
                <div class="form-group">
                    <% unless params[:email] %>
                        <input type="submit" value="Créer" class= "btn btn-outline-custom">
                    <% else %>
                        <input type="submit" value="Modifier" class= "btn btn-outline-custom" %>
                    <% end %>
                </div>
                
            </div>
        </div>
    <% end %>
</section>
<section class="dashboard-tableau">
    <h2>Liste des Administrateurs</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <th>Nom Prenom</th>
            <th>Email</th>
            <th>Telephone</th>
            <th>Adresse</th>
            <th>Action</th>
        </thead>
        <% @admins.each do |admin| %>
            <tr>
                <td><%= "#{admin.nom} #{admin.prenom}" %></td>
                <td><%= admin.email %></td>
                <td><%= admin.telephone %></td>
                <td><%= admin.adresse %></td>
                <td class="d-flex justify-content-around">

                        <% if admin.etat == true %>
                            <span class="badge badge-success">
                                <%= link_to "Activer", change_state_admin_path(admin.email), method: :put %>
                            </span>
                        <% else %>
                            <span class="badge badge-danger">
                                <%= link_to "Desactiver", change_state_admin_path(admin.email), method: :put %>
                            </span>
                        <% end %>
                        
                        <a href="<%= edit_admin_path(admin.email) %>">
                            <span class="fas fa-edit" alt="Modifier"></span>
                        </a>

                        <a href="<%= delete_admin_path(admin.email) %>" data-method="DELETE">
                            <span class="fas fa-trash" style="color: red;" alt="Supprimer"></span>
                        </a>

                        <a href="<%= profil_path(admin.email) %>">
                            <span class="fas fa-plus" alt="Developper"></span>
                        </a>
                </td>
            </tr>
        <% end %>
    </table>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/caracteristiques.html.erb
<% content_for :dashboard_content do %>
<section class="dashboard-form">
    <%= form_for @caracteristique, url: create_caracteristique_path, html: {class: "dashboard-form-content"} do |form| %>
      <div class="container">
            <% unless params[:libelle] %>
                <h3>Création d'une caracteristique</h3>
            <% else %>
                <h3>Modification de la caracteristique</h3>
            <% end %>
        <div class="row">
          <% if @caracteristique.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@caracteristique.errors.count, "error") %> prohibited this type from being saved:</h2>

              <ul>
                <% @caracteristique.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="input-group form-group">
            <%= form.text_field :libelle, class: "form-control", placeholder: 'Libelle' %>
          </div>

          <div class="input-group form-group">
            <%= form.text_field :icon, class: "form-control", placeholder: 'Icon' %>
          </div>
                <input type="hidden" name="libelle" value="<%=params[:libelle]%>" />

          <div class="form-group">
            <% unless params[:libelle] %>
                <%= form.submit "Création", class: "btn btn-outline-custom" %>
            <% else %>
                <%= form.submit "Modifier", class: "btn btn-outline-custom" %>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
</section>

<section class="dashboard-tableau">
    <h2>Liste des caracteristiques</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <th>Libelle</th>
            <th>Icon</th>
            <th>Action</th>
        </thead>
        <% @caracteristiques.each do |caracteristique| %>
            <tr>
              <td><%= caracteristique.libelle %></td>
              <td><span><i class="<%= caracteristique.icon %>"></i></span> <%= caracteristique.icon %></td>
              <td class="d-flex justify-content-around">
                <a href="<%= edit_caracteristique_path(caracteristique.libelle) %>">
                    <span class="fas fa-edit" alt="Modifier"></span>
                </a>
                <a href="<%= delete_caracteristique_path(caracteristique.libelle) %>" data-method="DELETE">
                    <span class="fas fa-trash" style="color: red;" alt="Supprimer"></span>
                </a>
                <a href="<%= show_caracteristique_path(caracteristique.libelle) %>">
                    <span class="fas fa-plus" alt="Detail"></span>
                </a>
              </td>
            </tr>
        <% end %>
    </table>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/index.html.erb
<% content_for :dashboard_content do %>
    <div class="jumbotron user-connecte">
        <h1 class="display-4">103677</h1>
        <div class="lead">Utilisateurs connectés</div>
    </div>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/locations.html.erb
<% content_for :dashboard_content do %>
<section class="dashboard-form">
    <%= render template: 'locations/_form' %>
</section>
<section class="dashboard-tableau">
    <h2>Liste des locations</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <th>Titre</th>
            <th>Adresse</th>
            <th>Prix</th>
            <th>Bailleur</th>
            <th>Action</th>
        </thead>
        <% @locations.each do |location| %>
            <tr>
                <td><%= location.titre %></td>
                <td><%= location.adresse %></td>
                <td><%= "#{location.prix} / #{location.duree}" %></td>
                <td><%= location.nom_bailleur %></td>
                <td class="d-flex justify-content-around">
                  <% if location.etat == true %>
                    <span class="badge badge-success">
                        <%= link_to "Activer", change_state_location_path(location.slug), method: :put %>
                    </span>
                  <% else %>
                    <span class="badge badge-danger">
                        <%= link_to "Desactiver", change_state_location_path(location.slug), method: :put %>
                    </span>
                  <% end %>
                  
                  <a href="<%= edit_location_path(location.slug) %>">
                    <span class="fas fa-edit" alt="Modifier"></span>
                  </a>

                  <a href="<%= location_path(location.slug) %>" data-method="DELETE">
                    <span class="fas fa-trash" style="color: red;" alt="Supprimer"></span>
                  </a>

                  <a href="<%= show_location_path(location.slug) %>">
                    <span class="fas fa-plus" alt="Detail"></span>
                  </a>
                </td>
            </tr>
        <% end %>
    </table>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/reservations.html.erb
<% content_for :dashboard_content do %>

<section>
    <div class="jumbotron">
        <h1 class="display-4">56</h1>
        <div class="lead">Locations reservées aujourd'hui</div>
    </div>
</section>

<section class="dashboard-tableau">
    <h2>Liste des reservations</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <th>Titre de la location</th>
            <th>Nom & Prenom</th>
            <th>Email</th>
            <th>Telephone</th>
            <th>Date de debut et fin</th>
            <th>Action</th>
        </thead>
        <% @reservations.each do |reservation| %>
            <tr>
                <td><%= reservation.location.titre %></td>
                <td><%= "#{reservation.nom} #{reservation.prenom}" %></td>
                <td><%= reservation.email %></td>
                <td><%= reservation.telephone %></td>
                <td><%= "#{reservation.debut} - #{reservation.fin}" %></td>
                <td class="d-flex justify-content-around">
                    <% if reservation.confirmer == true %>
                        <span class="badge badge-success">
                            Confirmer
                        </span>
                    <% else %>
                        <span class="badge badge-danger">
                            <%= link_to "Non confirmer", confirmer_path(reservation.slug) %>
                        </span>
                    <% end %>

                  <a href="<%= show_reservation_path(reservation.slug) %>">
                    <span class="fas fa-plus" alt="Detail"></span>
                  </a>
                </td>
            </tr>
        <% end %>
    </table>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/show_caracteristique.html.erb
<% content_for :dashboard_content do %>
<section>
    <%= render template: 'caracteristiques/show' %>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/show_location.html.erb
<% content_for :dashboard_content do %>
<section>
    <%= render template: 'locations/show' %>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/show_reservation.html.erb
<% content_for :dashboard_content do %>
<section>
    <%= render template: 'reservations/show' %>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/show_type.html.erb
<% content_for :dashboard_content do %>
<section>
    <%= render template: 'types/show' %>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/types.html.erb
<% content_for :dashboard_content do %>
<section class="dashboard-form">
    <%= form_for @type, url: create_type_path, html: {class: "dashboard-form-content"} do |form| %>
      <div class="container">
            <% unless params[:slug] %>
                <h3>Création d'un type</h3>
            <% else %>
                <h3>Modification du type</h3>
            <% end %>
        <div class="row">
          <% if @type.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

              <ul>
                <% @type.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="input-group form-group">
            <%= form.text_field :libelle, class: "form-control", placeholder: 'Libelle' %>
          </div>

          <div class="input-group form-group">
            <%= form.label :etat, class: "input-group-text" %>
            <%= form.check_box :etat, class: "form-control" %>
          </div>

          <div class="input-group form-group">
            <%= form.label :image, class: "input-group-text" %>
            <%= form.file_field :image, class: "form-control" %>
          </div>

          <div class="input-group form-group">
            <%= form.hidden_field :user_id %>
                <input type="hidden" name="slug" value="<%=params[:slug]%>" />
          </div>

          <div class="form-group">
            <% unless params[:slug] %>
              <%= form.submit "Création", class: "btn btn-outline-custom" %>
            <% else %>
              <%= form.submit "Modifier", class: "btn btn-outline-custom" %>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
</section>

<section class="dashboard-tableau">
    <h2>Liste des types</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <th>Libelle</th>
            <th>Etat</th>
            <th>Action</th>
        </thead>
        <% @types.each do |type| %>
            <tr>
                <td><%= type.libelle %></td>
                <td><%= type.etat %></td>
                <td class="d-flex justify-content-around">
                  <a href="<%= edit_type_path(type.slug) %>">
                      <span class="fas fa-edit" alt="Modifier"></span>
                  </a>

                  <a href="<%= delete_type_path(type.slug) %>" data-method="DELETE">
                      <span class="fas fa-trash" style="color: red;" alt="Supprimer"></span>
                  </a>

                  <a href="<%= show_type_path(type.slug) %>">
                      <span class="fas fa-plus" alt="Detail"></span>
                  </a>
                </td>
            </tr>
        <% end %>
    </table>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>

app/views/dashboards/utilisateurs.html.erb
<% content_for :dashboard_content do %>

<section>
    <div class="jumbotron">
        <h1 class="display-4">103677</h1>
        <div class="lead">Utilisateurs inscrits</div>
    </div>
</section>
<section class="dashboard-tableau">
    <h2>Liste des utilisateurs</h2>
    <table class="table table-bordered table-hover">
        <thead>
            <th>Nom Prenom</th>
            <th>Email</th>
            <th>Telephone</th>
            <th>Nombre de reservation</th>
            <th>Action</th>
        </thead>
        <% @users.each do |user| %>
            <tr>
                <td><%= "#{user.nom} #{user.prenom}" %></td>
                <td><%= user.email %></td>
                <td><%= user.telephone %></td>
                <td>8</td>
                <td class="d-flex justify-content-around">
                  <% if user.etat == true %>
                    <span class="badge badge-success">
                        <%= link_to "Activer", change_state_user_path(user.email), method: :put %>
                    </span>
                  <% else %>
                    <span class="badge badge-danger">
                        <%= link_to "Desactiver", change_state_user_path(user.email), method: :put %>
                    </span>
                  <% end %>
                  
                  <a href="<%= edit_admin_path(user.email) %>">
                    <span class="fas fa-edit" alt="Modifier"></span>
                  </a>

                  <a href="<%= delete_user_path(user.email) %>" data-method="DELETE">
                    <span class="fas fa-trash" style="color: red;" alt="Supprimer"></span>
                  </a>

                  <a href="<%= profil_path(user.email) %>">
                    <span class="fas fa-plus" alt="Developper"></span>
                  </a>
                </td>
            </tr>
        <% end %>
    </table>
</section>
<% end %>

<%= render template: 'pages/dashboard' %>